name: verify-push

on:
  push:
    branches-ignore:
      - 'master' #no need to run after merging to master
    tags-ignore:
      - '*' #do not run on pushing tags (see deploy-on-release-created)
  pull_request:

jobs:
  verify:
    #run if push or pull_requests from fork
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        module:
          - matsim
          - contribs/cadytsIntegration
          - contribs/dvrp
          - benchmark

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: Detect changes against master
        # we only want to build matsim (module) if changes are not limited to contribs
        id: detect-changes
        uses: dorny/paths-filter@v2
        if: ${{matrix.module == 'matsim'}}
        with:
          filters: |
            outside-contribs:
              - '!contribs/**'

      - name: Cache local Maven repository
        uses: actions/cache@v2
        if: ${{matrix.module != 'matsim' || steps.detect-changes.outputs.outside-contribs == 'true'}}
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup Java
        if: ${{matrix.module != 'matsim' || steps.detect-changes.outputs.outside-contribs == 'true'}}
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Build module (with dependencies)
        if: ${{matrix.module != 'matsim' || steps.detect-changes.outputs.outside-contribs == 'true'}}
        run: mvn install --batch-mode --also-make --projects ${{matrix.module}} -DskipTests -Dsource.skip

      - name: Test module
        if: ${{matrix.module != 'matsim' || steps.detect-changes.outputs.outside-contribs == 'true'}}
        run: mvn verify --batch-mode -Dmaven.test.redirectTestOutputToFile -Dmatsim.preferLocalDtds=true --fail-at-end -Dsource.skip
        working-directory: ${{matrix.module}}

    env:
      MAVEN_OPTS: -Xmx2g

  verify-all-jobs-successful:
    if: ${{ always() }}
    needs: verify
    runs-on: ubuntu-latest
    steps:
      - name: all jobs successful
        if: ${{ needs.verify.result != 'success' }}
        run: exit 1


